// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using OpenCnpj.Infraestructure.DbContexts;

#nullable disable

namespace OpenCnpj.Infraestructure.Migrations
{
    [DbContext(typeof(OpenCnpjDbContext))]
    [Migration("20250905193114_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "public", "age_ranges", new[] { "not_applicable", "from0to12", "from13to20", "from21to30", "from31to40", "from41to50", "from51to60", "from61to70", "from71to80", "over80" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "public", "application_steps", new[] { "application_step", "downloading_files", "extracting_files", "processing_raw_files", "formatting_raw_data" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "public", "company_situations", new[] { "null", "active", "suspense", "inapt", "closed" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "public", "company_sizes", new[] { "not_informed", "micro_company", "small_company", "other" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "public", "company_types", new[] { "head_office", "branch" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "public", "file_statuses", new[] { "downloading", "created", "processing", "processed", "deleted" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "public", "partner_types", new[] { "legal_entity", "individual", "foreign" });
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("OpenCnpj.Application.AddressTypes.Domain.AddressType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.HasKey("Id");

                    b.ToTable("address_types", (string)null);
                });

            modelBuilder.Entity("OpenCnpj.Application.Addresses.Domain.Address", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("AddressTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("address_type_id");

                    b.Property<long>("CityId")
                        .HasColumnType("bigint")
                        .HasColumnName("city_id");

                    b.Property<string>("Complement")
                        .HasColumnType("text")
                        .HasColumnName("complement");

                    b.Property<string>("FederalUnit")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("federal_unit");

                    b.Property<string>("Neighborhood")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("neighborhood");

                    b.Property<int?>("Number")
                        .HasColumnType("integer")
                        .HasColumnName("number");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("street");

                    b.Property<int?>("ZipCode")
                        .HasColumnType("integer")
                        .HasColumnName("zip_code");

                    b.HasKey("Id");

                    b.HasIndex("AddressTypeId");

                    b.HasIndex("CityId");

                    b.ToTable("addresses", (string)null);
                });

            modelBuilder.Entity("OpenCnpj.Application.Batches.BatchFiles.Domain.BatchFile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BatchId")
                        .HasColumnType("integer")
                        .HasColumnName("batch_id");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("file_name");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("file_path");

                    b.Property<int>("FileStatus")
                        .HasColumnType("integer")
                        .HasColumnName("file_status_id");

                    b.HasKey("Id");

                    b.ToTable("batch_files", (string)null);
                });

            modelBuilder.Entity("OpenCnpj.Application.Batches.Batches.Domain.Batch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ApplicationLastStep")
                        .HasColumnType("integer")
                        .HasColumnName("application_last_step_id");

                    b.Property<string>("Directory")
                        .HasColumnType("text");

                    b.Property<string>("Identifier")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("identifier");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("Identifier")
                        .IsUnique();

                    b.ToTable("batches", (string)null);
                });

            modelBuilder.Entity("OpenCnpj.Application.Cities.Domain.City", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("Code")
                        .HasColumnType("bigint")
                        .HasColumnName("code");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("cities", (string)null);
                });

            modelBuilder.Entity("OpenCnpj.Application.Companies.Domain.Company", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("AddressId")
                        .HasColumnType("bigint")
                        .HasColumnName("address_id");

                    b.Property<int>("CompanySize")
                        .HasColumnType("integer")
                        .HasColumnName("company_size_id");

                    b.Property<long?>("CompanySpecialSituationId")
                        .HasColumnType("bigint")
                        .HasColumnName("company_special_situation_id");

                    b.Property<int>("CompanyType")
                        .HasColumnType("integer")
                        .HasColumnName("company_type_id");

                    b.Property<long?>("CountryId")
                        .HasColumnType("bigint")
                        .HasColumnName("country_id");

                    b.Property<string>("FantasyName")
                        .HasColumnType("text")
                        .HasColumnName("fantasy_name");

                    b.Property<string>("ForeingCityName")
                        .HasColumnType("text")
                        .HasColumnName("foreign_city_name");

                    b.Property<string>("Identifier")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("identifier");

                    b.Property<long>("LegalNatureId")
                        .HasColumnType("bigint")
                        .HasColumnName("legal_nature_id");

                    b.Property<long>("MainEconomicActivityId")
                        .HasColumnType("bigint")
                        .HasColumnName("main_economic_activity_id");

                    b.Property<long?>("MainPartnerQualificationId")
                        .HasColumnType("bigint")
                        .HasColumnName("main_partner_qualification_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<DateTime?>("RegisterDate")
                        .HasColumnType("timestamptz")
                        .HasColumnName("register_date");

                    b.Property<string>("ResponsableFederativeEntity")
                        .HasColumnType("text")
                        .HasColumnName("responsabile_federative_entity");

                    b.Property<decimal>("ShareCapital")
                        .HasColumnType("decimal")
                        .HasColumnName("share_capital");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamptz")
                        .HasColumnName("start_date");

                    b.HasKey("Id");

                    b.HasIndex("AddressId");

                    b.HasIndex("CompanySpecialSituationId");

                    b.HasIndex("CountryId");

                    b.HasIndex("LegalNatureId");

                    b.HasIndex("MainEconomicActivityId");

                    b.HasIndex("MainPartnerQualificationId");

                    b.ToTable("company", (string)null);
                });

            modelBuilder.Entity("OpenCnpj.Application.CompanySpecialSituations.Domain.CompanySpecialSituation", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("SpecialSituationId")
                        .HasColumnType("integer")
                        .HasColumnName("special_situation_id");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.HasKey("Id");

                    b.HasIndex("SpecialSituationId");

                    b.ToTable("company_special_situations", (string)null);
                });

            modelBuilder.Entity("OpenCnpj.Application.Countries.Domain.Country", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("code");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("countries", (string)null);
                });

            modelBuilder.Entity("OpenCnpj.Application.EconomicActivities.Domain.EconomicActivity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("code");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("economic_activities", (string)null);
                });

            modelBuilder.Entity("OpenCnpj.Application.IndividualMicroentrepreneurs.Domain.IndividualMicroentrepreneur", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateOnly?>("DateOpted")
                        .HasColumnType("date")
                        .HasColumnName("date_opted");

                    b.Property<DateOnly?>("ExclusionDate")
                        .HasColumnType("date")
                        .HasColumnName("exclusion_date");

                    b.HasKey("Id");

                    b.ToTable("individual_microentrepreneurs", (string)null);
                });

            modelBuilder.Entity("OpenCnpj.Application.LegalNatures.Domain.LegalNature", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("code");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("legal_natures", (string)null);
                });

            modelBuilder.Entity("OpenCnpj.Application.LegalRepresentatives.Domain.LegalRepresentative", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Identifier")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PartnerQualificationId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("LegalRepresentative");
                });

            modelBuilder.Entity("OpenCnpj.Application.Partners.Domain.Partner", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("AgeRange")
                        .HasColumnType("integer")
                        .HasColumnName("age_range_id");

                    b.Property<long>("CompanyId")
                        .HasColumnType("bigint")
                        .HasColumnName("company_id");

                    b.Property<long?>("CountryId")
                        .HasColumnType("bigint")
                        .HasColumnName("country_id");

                    b.Property<string>("Identifier")
                        .HasColumnType("text")
                        .HasColumnName("identifier");

                    b.Property<long?>("LegalRepresentativeId")
                        .HasColumnType("bigint")
                        .HasColumnName("legal_representative_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<long>("PartnerQualificationId")
                        .HasColumnType("bigint")
                        .HasColumnName("partner_qualification_id");

                    b.Property<int>("PartnerType")
                        .HasColumnType("integer")
                        .HasColumnName("partner_type_id");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("CountryId");

                    b.HasIndex("LegalRepresentativeId");

                    b.HasIndex("PartnerQualificationId");

                    b.ToTable("partners", (string)null);
                });

            modelBuilder.Entity("OpenCnpj.Application.PartnersQualifications.Domain.PartnerQualification", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("Code")
                        .HasColumnType("bigint")
                        .HasColumnName("code");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("partner_qualifications", (string)null);
                });

            modelBuilder.Entity("OpenCnpj.Application.Phones.Domain.Phone", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("AreaCode")
                        .HasColumnType("integer")
                        .HasColumnName("area_code");

                    b.Property<int>("PhoneNumber")
                        .HasColumnType("integer")
                        .HasColumnName("phone");

                    b.HasKey("Id");

                    b.ToTable("phones", (string)null);
                });

            modelBuilder.Entity("OpenCnpj.Application.Reasons.Domain.Reason", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("code");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("reasons", (string)null);
                });

            modelBuilder.Entity("OpenCnpj.Application.SpecialSituations.Domain.SpecialSituation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.HasKey("Id");

                    b.ToTable("special_situations", (string)null);
                });

            modelBuilder.Entity("OpenCnpj.Application.Addresses.Domain.Address", b =>
                {
                    b.HasOne("OpenCnpj.Application.AddressTypes.Domain.AddressType", "AddressType")
                        .WithMany()
                        .HasForeignKey("AddressTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_addresses_address_types");

                    b.HasOne("OpenCnpj.Application.Cities.Domain.City", "City")
                        .WithMany()
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_addresses_cities");

                    b.Navigation("AddressType");

                    b.Navigation("City");
                });

            modelBuilder.Entity("OpenCnpj.Application.Companies.Domain.Company", b =>
                {
                    b.HasOne("OpenCnpj.Application.Addresses.Domain.Address", "Address")
                        .WithMany()
                        .HasForeignKey("AddressId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired()
                        .HasConstraintName("FK_companies_addresses");

                    b.HasOne("OpenCnpj.Application.CompanySpecialSituations.Domain.CompanySpecialSituation", "CompanySpecialSituation")
                        .WithMany()
                        .HasForeignKey("CompanySpecialSituationId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_companies_companies_special_situations");

                    b.HasOne("OpenCnpj.Application.Countries.Domain.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_companies_countries");

                    b.HasOne("OpenCnpj.Application.LegalNatures.Domain.LegalNature", "LegalNature")
                        .WithMany()
                        .HasForeignKey("LegalNatureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_companies_legal_natures");

                    b.HasOne("OpenCnpj.Application.EconomicActivities.Domain.EconomicActivity", "MainEconomicActivity")
                        .WithMany()
                        .HasForeignKey("MainEconomicActivityId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired()
                        .HasConstraintName("FK_companies_economic_activities");

                    b.HasOne("OpenCnpj.Application.PartnersQualifications.Domain.PartnerQualification", "MainPartnerQualification")
                        .WithMany()
                        .HasForeignKey("MainPartnerQualificationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK_companies_partner_qualifications");

                    b.Navigation("Address");

                    b.Navigation("CompanySpecialSituation");

                    b.Navigation("Country");

                    b.Navigation("LegalNature");

                    b.Navigation("MainEconomicActivity");

                    b.Navigation("MainPartnerQualification");
                });

            modelBuilder.Entity("OpenCnpj.Application.CompanySpecialSituations.Domain.CompanySpecialSituation", b =>
                {
                    b.HasOne("OpenCnpj.Application.SpecialSituations.Domain.SpecialSituation", "SpecialSituation")
                        .WithMany()
                        .HasForeignKey("SpecialSituationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_company_special_situations_special_situations");

                    b.Navigation("SpecialSituation");
                });

            modelBuilder.Entity("OpenCnpj.Application.Partners.Domain.Partner", b =>
                {
                    b.HasOne("OpenCnpj.Application.Companies.Domain.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_partners_company");

                    b.HasOne("OpenCnpj.Application.Countries.Domain.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_partners_country");

                    b.HasOne("OpenCnpj.Application.LegalRepresentatives.Domain.LegalRepresentative", "LegalRepresentative")
                        .WithMany()
                        .HasForeignKey("LegalRepresentativeId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_partners_legal_representative");

                    b.HasOne("OpenCnpj.Application.PartnersQualifications.Domain.PartnerQualification", "PartnerQualification")
                        .WithMany()
                        .HasForeignKey("PartnerQualificationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_partners_partner_qualification");

                    b.Navigation("Company");

                    b.Navigation("Country");

                    b.Navigation("LegalRepresentative");

                    b.Navigation("PartnerQualification");
                });
#pragma warning restore 612, 618
        }
    }
}
