services:
  opencnpj:
    build: .
    container_name: OpenCNPJ
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    environment:
      - ConnectionStrings__MongoDB=mongodb://mongodb:27017

  mongodb:
    image: mongo
    container_name: OpenCNPJMongoDB
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
