<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net9.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="CSharpFunctionalExtensions" Version="3.6.0" />
		<PackageReference Include="Dapper" Version="2.1.66" />
		<PackageReference Include="Microsoft.Data.Sqlite" Version="9.0.11" />
		<PackageReference Include="Microsoft.Data.Sqlite.Core" Version="9.0.11" />
		<PackageReference Include="Microsoft.Extensions.Diagnostics.HealthChecks" Version="8.0.11" />
		<PackageReference Include="MongoDB.Driver" Version="3.4.3" />
		<PackageReference Include="MongoDB.Driver" Version="3.4.3" />
		<PackageReference Include="FluentMigrator" Version="7.1.0" />
		<PackageReference Include="FluentMigrator.Extensions.Postgres" Version="7.1.0" />
		<PackageReference Include="FluentMigrator.Runner" Version="7.1.0" />
		<PackageReference Include="Polly" Version="8.6.3" />
		<PackageReference Include="Serilog" Version="4.3.0" />

	</ItemGroup>

</Project>
